Add fixers and more output
rnpnr/vis-lint pull request #2
Opened 2023-04-16 15:37 UTC by roguh

This will add more logging, such as printing the command before running it or printing `[no output]`. Also adds the option to add multiple linters per file type.

I also added the ability to run `fixers`, which may modify the file. This can be used for formatters or linters with a `--fix` option, like `ruff --fix` and `orange` for Python, `cargo clippy --fix` for Rust, or `jq -c` for JSON.

2023-04-16 16:41 UTC, rnpnr commented
Hi Hugo, thanks for the patch! Some comments:

- I made a change to pipe the file contents to the command so that you don't have to write the file before linting. Can you adjust your patch to maintain that behavior if possible?
- Please don't switch tabs to spaces. That way I can have my 8 char tabstop and you can have your 4 char tabstop and we are both happy.

More comments inline:

2023-04-16 16:44 UTC, rnpnr requested changes

2023-04-16 16:44 UTC, rnpnr commented on init.lua
> +          vis:message('[no output]')
Ideally this should go to the info bar and only when all of the commands have no output.

2023-04-16 16:44 UTC, rnpnr commented on init.lua
> +fixers["rust"] = {"cargo fmt", "cargo clippy --fix"}
Please keep these lists sorted.

2023-04-16 16:44 UTC, rnpnr commented on init.lua
> +        return false
This shouldn't be necessary if contents from the buffer are piped to the command.

2023-04-16 16:46 UTC, rnpnr commented
I also forgot to add that I am going to assume that the commands you have added are somewhat "standard" since I don't really use any of those languages. When I have time I would like to make the linters configurable with these being the defaults.

2023-05-04 04:47 UTC, rnpnr commented
Hi Hugo,
I cleaned up the main issues I had. This can be merged if I can get some confirmation that the linters and fixers you added accept file contents on `stdin` and write the results to `stdout`.

2023-05-14 15:53 UTC, roguh commented on init.lua
> +          vis:message('[no output]')
I'll just remove that.

2023-05-14 15:54 UTC, roguh commented
Hey, sorry for dropping off, life got quite busy. I'll double check that the commands are standard and work well stdin and stdout for I/O.

Piping output into commands will handle the edge case of opening `stdin`, e.g. as an interactive editor within a sequence of piped commands. Mainly, it'll avoid problems with temporary files or writing to disk automatically. Good idea!

> Please don't switch tabs to spaces. That way I can have my 8 char tabstop and you can have your 4 char tabstop and we are both happy.

Got it!

2023-05-14 21:58 UTC, rnpnr approved these changes

2023-05-14 22:05 UTC, rnpnr commented
These changes look good to me. I'm fine with merging as is now.

I'm going to make the fixers and linters configurable soon. When I do so I think I only want to keep at most 2 default fixers/linters. Do you have a preference for `python`? Maybe `black` and `isort`?

It will be really easy to add more to the defaults in `visrc.lua` so don't worry about losing the others.

2023-05-16 13:46 UTC, roguh commented
For Python, I suggest `black`, `isort`, and `pylint`.

Can you leave the other ones in there somewhere? I'd want users to have these commands that are compatible with stdin/stdout but only a few should be enabled by default. The `mypy <(cat)` command is especially esoteric. Perhaps a table mapping a language + linter/fixer and its stdout/stdin command?

2023-05-17 01:53 UTC, roguh commented
I wrote up a little something so other people can find this `mypy <(cat)` solution: https://felina.cloud/how-to-send-stdin-to-mypy

2023-05-17 03:11 UTC, merged